# PATCH  http://localhost:1234/movies/8
# Content-Type: application/json

# {
#         "title": "La Anaconda",
#         "director" : "Steven Spilberg"
# }


#  GET http://localhost:1234/movies


# DELETE http://localhost:1234/movies/3



 POST http://localhost:1234/movies 
 Content-Type: application/json

{
        "title" : "Locos Adams",
        "year" : 2023,
        "director": "Melocoton",
        "duration": 170,
        "genre": ["Animacion"]
}
